#!/usr/bin/env python3
"""Regenerate README.md, docs/index.html and exports/ from tools/*.yml + categories.yml.

Deterministic: output depends only on the source files.
"""
import csv
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

ACCESS_LABEL = {
    "free": "Free",
    "freemium": "Freemium",
    "paid": "Paid",
    "institutional": "Institutional",
    "waitlist": "Waitlist",
    "unknown": "—",
}


def load():
    categories = yaml.safe_load((ROOT / "categories.yml").read_text())
    tools = []
    for f in sorted((ROOT / "tools").glob("*.yml")):
        t = yaml.safe_load(f.read_text())
        t["slug"] = f.stem
        tools.append(t)
    order = {slug: i for i, slug in enumerate(categories)}
    tools.sort(key=lambda t: (order.get(t["category"], 99), t["name"].casefold()))
    return categories, tools


def build_readme(categories, tools):
    active = [t for t in tools if t["status"] in ("active", "needs-review")]
    candidates = [t for t in tools if t["status"] == "candidate"]
    retired = [t for t in tools if t["status"] in ("deprecated", "acquired")]
    verified_dates = [t["last_verified"] for t in tools if t.get("last_verified")]
    last_verified = max(verified_dates) if verified_dates else "never"

    lines = [
        "# AI Tools for Scientific Research",
        "",
        "A curated, verified catalog of AI tools that are genuinely usable in academic",
        "research — maintained by [Michaela Liegertová](https://www.ujep.cz/), updated with",
        "each course edition.",
        "",
        f"**{len(active)} tools** across **{len(categories)} categories** · last verification"
        f" pass: {last_verified}",
        "",
        "The goal is **task diversity, not exhaustiveness**: each category shows a small,"
        " deliberately varied palette of tools the academic community actually uses"
        " (*core*), with further options collapsed underneath (*extended*). For depth in"
        " specific areas, see the companion [AI for Science indexes]"
        "(https://michalie.github.io/) — Biological Foundation Models, Autonomous Science"
        " Agents, and privacy-first Coding & Data Agents.",
        "",
        "> Generated from [`tools/`](tools/) by `scripts/build.py` — do not edit this file"
        " by hand. Browsable version: [`docs/index.html`](docs/index.html).",
        "",
        "## Categories",
        "",
    ]
    for slug, meta in categories.items():
        n = sum(1 for t in active if t["category"] == slug)
        if n:
            anchor = meta["title"].lower().replace(" ", "-").replace("&", "").replace("--", "-")
            lines.append(f"- [{meta['title']}](#{anchor}) ({n})")
    lines.append("")

    for slug, meta in categories.items():
        cat_tools = [t for t in active if t["category"] == slug]
        if not cat_tools:
            continue
        lines += [f"## {meta['title']}", ""]
        if meta.get("blurb"):
            lines += [f"*{meta['blurb']}*", ""]
        if meta.get("deep_dive"):
            dd = meta["deep_dive"]
            lines += [f"🔎 Going deeper: [{dd['title']}]({dd['url']})", ""]

        def row(t):
            flag = " ⚠️" if t["status"] == "needs-review" else ""
            provider = t.get("provider") or "—"
            desc = t["description"].replace("|", "\\|").replace("\n", " ")
            return (f"| [{t['name']}]({t['url']}){flag} | {provider} |"
                    f" {ACCESS_LABEL[t['access']]} | {desc} |")

        header = ["| Tool | Provider | Access | Description |", "|---|---|---|---|"]
        core = [t for t in cat_tools if t.get("tier") == "core"]
        ext = [t for t in cat_tools if t.get("tier") != "core"]
        lines += header + [row(t) for t in core] + [""]
        if ext:
            lines += [f"<details><summary>More tools for this task ({len(ext)})</summary>",
                      ""] + header + [row(t) for t in ext] + ["", "</details>", ""]

    if candidates:
        lines += ["## Watchlist", "", "Captured but not yet vetted against the admission gate.", ""]
        for t in candidates:
            lines.append(f"- [{t['name']}]({t['url']}) — {t.get('notes') or t['description']}")
        lines.append("")
    if retired:
        lines += ["## Retired", "", "Kept for the historical record.", ""]
        for t in retired:
            lines.append(f"- **{t['name']}** ({t['status']}) — {t.get('notes') or t['description']}")
        lines.append("")

    lines += [
        "---",
        "",
        "⚠️ = pending re-verification. Maintenance protocol: see [CLAUDE.md](CLAUDE.md).",
        "",
    ]
    (ROOT / "README.md").write_text("\n".join(lines))


def build_exports(categories, tools):
    out = ROOT / "exports"
    out.mkdir(exist_ok=True)
    payload = {
        "title": "AI Tools for Scientific Research",
        "categories": categories,
        "tools": tools,
    }
    (out / "tools.json").write_text(json.dumps(payload, indent=1, ensure_ascii=False) + "\n")
    with (out / "tools.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["category", "name", "provider", "url", "description", "access",
                    "domain", "status", "tier", "added", "last_verified"])
        for t in tools:
            w.writerow([categories[t["category"]]["title"], t["name"], t.get("provider") or "",
                        t["url"], t["description"], t["access"], t["domain"], t["status"],
                        t.get("tier", ""), t["added"], t.get("last_verified") or ""])


def build_site(categories, tools):
    (ROOT / "docs").mkdir(exist_ok=True)
    payload = json.dumps({"categories": categories, "tools": tools}, ensure_ascii=False)
    html = TEMPLATE.replace("__DATA__", payload.replace("</", "<\\/"))
    (ROOT / "docs" / "index.html").write_text(html)


TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI Tools for Scientific Research</title>
<style>
  :root {
    --bg: #f7f7f5; --panel: #ffffff; --ink: #1a1a20; --muted: #6b6b74;
    --line: #e4e4e0; --accent: #275e5a; --accent-ink: #ffffff; --chip: #ecece8;
    --flag: #9a6b00;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #16161a; --panel: #1f1f25; --ink: #ececf0; --muted: #9a9aa4;
      --line: #2e2e36; --accent: #57a49e; --accent-ink: #10201e; --chip: #2a2a31;
      --flag: #d9a53a;
    }
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--ink);
         font: 15px/1.5 -apple-system, "Segoe UI", system-ui, sans-serif; }
  header { padding: 2.2rem 1.2rem 1.2rem; max-width: 62rem; margin: 0 auto; }
  h1 { margin: 0 0 .2rem; font-size: 1.5rem; letter-spacing: -.01em; }
  .sub { color: var(--muted); margin: 0 0 1.1rem; }
  .controls { display: flex; flex-wrap: wrap; gap: .5rem; align-items: center; }
  input[type=search], select {
    background: var(--panel); color: var(--ink); border: 1px solid var(--line);
    border-radius: .55rem; padding: .5rem .7rem; font: inherit;
  }
  input[type=search] { flex: 1 1 14rem; }
  .count { color: var(--muted); font-size: .85rem; margin-left: auto; }
  main { max-width: 62rem; margin: 0 auto; padding: 0 1.2rem 4rem; }
  h2.cat { font-size: 1.02rem; margin: 1.8rem 0 .15rem; padding-bottom: .3rem;
           border-bottom: 1px solid var(--line); }
  h2.cat small { color: var(--muted); font-weight: 400; }
  .blurb { color: var(--muted); font-style: italic; margin: 0 0 .3rem; font-size: .9rem; }
  a.deep { display: inline-block; font-size: .85rem; color: var(--accent);
           text-decoration: none; margin: 0 0 .6rem; }
  a.deep:hover { text-decoration: underline; }
  details.more { margin: .1rem 0 .9rem; }
  details.more summary { cursor: pointer; color: var(--muted); font-size: .85rem;
                         padding: .25rem 0; user-select: none; }
  details.more .tool { opacity: .88; }
  .tool { background: var(--panel); border: 1px solid var(--line);
          border-radius: .7rem; padding: .7rem .9rem; margin: 0 0 .5rem; }
  .row1 { display: flex; flex-wrap: wrap; gap: .45rem; align-items: baseline; }
  .tool a.name { color: var(--accent); font-weight: 600; text-decoration: none; }
  .tool a.name:hover { text-decoration: underline; }
  .prov { color: var(--muted); font-size: .85rem; }
  .badge { font-size: .72rem; padding: .1rem .5rem; border-radius: 99px;
           background: var(--chip); color: var(--muted); white-space: nowrap; }
  .badge.free, .badge.freemium { background: var(--accent); color: var(--accent-ink); }
  .badge.review { background: transparent; border: 1px solid var(--flag); color: var(--flag); }
  .desc { margin: .25rem 0 0; color: var(--ink); }
  .empty { color: var(--muted); padding: 2rem 0; text-align: center; }
  footer { max-width: 62rem; margin: 0 auto; padding: 0 1.2rem 2.5rem;
           color: var(--muted); font-size: .85rem; }
</style>
</head>
<body>
<header>
  <h1>AI Tools for Scientific Research</h1>
  <p class="sub">Curated &amp; verified for academic use · Michaela Liegertová</p>
  <div class="controls">
    <input type="search" id="q" placeholder="Search tools, providers, descriptions…">
    <select id="cat"><option value="">All categories</option></select>
    <select id="acc">
      <option value="">Any access</option>
      <option value="free">Free</option><option value="freemium">Freemium</option>
      <option value="paid">Paid</option><option value="institutional">Institutional</option>
    </select>
    <span class="count" id="count"></span>
  </div>
</header>
<main id="list"></main>
<footer>Generated from the repository’s <code>tools/</code> directory — the page is a
build artifact; edits belong in the YAML source.</footer>
<script>
const DATA = __DATA__;
const ACCESS = {free:"Free", freemium:"Freemium", paid:"Paid",
                institutional:"Institutional", waitlist:"Waitlist", unknown:"Access?"};
const q = document.getElementById("q"), cat = document.getElementById("cat"),
      acc = document.getElementById("acc"), list = document.getElementById("list"),
      count = document.getElementById("count");
for (const [slug, meta] of Object.entries(DATA.categories)) {
  const o = document.createElement("option"); o.value = slug; o.textContent = meta.title;
  cat.appendChild(o);
}
const esc = s => (s || "").replace(/[&<>"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const card = t => `<div class="tool"><div class="row1">
      <a class="name" href="${esc(t.url)}" target="_blank" rel="noopener">${esc(t.name)}</a>
      ${t.provider ? `<span class="prov">${esc(t.provider)}</span>` : ""}
      <span class="badge ${esc(t.access)}">${ACCESS[t.access]}</span>
      ${t.domain === "life-sciences" ? `<span class="badge">life sciences</span>` : ""}
      ${t.status === "needs-review" ? `<span class="badge review">needs review</span>` : ""}
      </div><p class="desc">${esc(t.description)}</p></div>`;
function render() {
  const term = q.value.trim().toLowerCase();
  const filtering = !!(term || cat.value || acc.value);
  const match = t =>
    (t.status === "active" || t.status === "needs-review") &&
    (!cat.value || t.category === cat.value) &&
    (!acc.value || t.access === acc.value) &&
    (!term || (t.name + " " + (t.provider||"") + " " + t.description).toLowerCase().includes(term));
  let html = "", nCore = 0, nExt = 0;
  for (const [slug, meta] of Object.entries(DATA.categories)) {
    const inCat = DATA.tools.filter(t => t.category === slug && match(t));
    if (!inCat.length) continue;
    const core = inCat.filter(t => t.tier === "core");
    const ext = inCat.filter(t => t.tier !== "core");
    nCore += core.length; nExt += ext.length;
    html += `<h2 class="cat">${esc(meta.title)} <small>· ${inCat.length}</small></h2>`;
    if (meta.blurb) html += `<p class="blurb">${esc(meta.blurb)}</p>`;
    if (meta.deep_dive) html += `<a class="deep" href="${esc(meta.deep_dive.url)}"
      target="_blank" rel="noopener">🔎 Going deeper: ${esc(meta.deep_dive.title)} ↗</a>`;
    html += core.map(card).join("");
    if (ext.length) html += `<details class="more"${filtering ? " open" : ""}>
      <summary>More tools for this task (${ext.length})</summary>${ext.map(card).join("")}</details>`;
  }
  list.innerHTML = html || `<p class="empty">Nothing matches.</p>`;
  count.textContent = `${nCore} core · ${nExt} extended`;
}
q.addEventListener("input", render); cat.addEventListener("change", render);
acc.addEventListener("change", render); render();
</script>
</body>
</html>
"""


def main():
    categories, tools = load()
    build_readme(categories, tools)
    build_exports(categories, tools)
    build_site(categories, tools)
    print(f"built: README.md, docs/index.html, exports/ — {len(tools)} tools,"
          f" {len(categories)} categories")


if __name__ == "__main__":
    main()
